# Generated by Django 5.2.2 on 2025-06-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='difficulty',
            field=models.CharField(choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], default='orta', max_length=10),
            preserve_default=False,
        ),
    ]
