# Generated by Django 5.1.7 on 2025-04-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schedule_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
